version: "3"
services:
  pgprovider:
    build: ./provider
    environment:
      - POSTGRES_PASSWORD=s3cr3t
    volumes:
      - ./postgresql.conf:/usr/share/postgresql/11/postgresql.conf.sample
      - ./pg_hba.conf:/usr/share/postgresql/11/pg_hba.conf.sample
    ports:
      - 5432:5432
  pgsubscriber:
    build: ./subscriber
    depends_on:
      - "pgprovider"
    environment:
      - POSTGRES_PASSWORD=s3cr3t
    volumes:
      - ./postgresql.conf:/usr/share/postgresql/11/postgresql.conf.sample
      - ./pg_hba.conf:/usr/share/postgresql/11/pg_hba.conf.sample
    ports:
      - 5433:5432
  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  pgexporter:
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:s3cr3t@pgprovider:5432?sslmode=disable,postgresql://postgres:s3cr3t@pgsubscriber:5432?sslmode=disable
      - PG_EXPORTER_DISABLE_SETTINGS_METRICS=true
      - PG_EXPORTER_EXTEND_QUERY_PATH=/config/queries.yaml
    image: wrouesnel/postgres_exporter
    volumes:
      - ./queries.yml:/config/queries.yaml
    ports:
      - 9187:9187
    depends_on:
      - pgprovider
      - pgsubscriber
  grafana:
    image: grafana/grafana:8.1.0
    ports:
      - 3000:3000
    depends_on:
      - prometheus
