version: "3"
services:
  provider:
    build: ./provider
    environment:
      - POSTGRES_PASSWORD=s3cr3t
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - pg_cluster
  subscriber:
    build: ./subscriber
    environment:
      - POSTGRES_PASSWORD=s3cr3t
    ports:
      - 5999:5432
    networks:
      default:
        aliases:
          - pg_cluster
